# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.10hacks.com
title: A Hackerpress Blog
subtitle: A blogging framework for hackers
author: Joe Johnston
description:

search:
  simple: http://google.com/search

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

rss:
  feed_url: /atom.xml
  email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:categories/:title/
source: ./source
destination: ./_public
plugins: ./_plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Jekyll-assets config
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - images
    - _assets/javascript
    - _vendor/javascript
    - _assets/stylesheets
    - _vendor/stylesheets
    - _vendor
  # compress:
  #   js: uglifier
  #   css: sass
  cachebust: hard
  cache_assets: true
  gzip: [ text/css, application/javascript ]

# kramdown supports {:toc} and is about as fast as redcarpet
# http://kramdown.rubyforge.org/converter/html.html#toc
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false # pygments plugins are used instead

# rdiscount supports {:toc} but is a bit slower than redcarpet
# http://rdoc.info/github/davidfstr/rdiscount/master/RDiscount
rdiscount:
  toc_token: "{:toc}"
  extensions:
    - autolink
    - footnotes
    - smart
    - generate_toc

# redcarpet is fast but does not support {:toc} without modifying jekyll or using a plugin
# https://github.com/vmg/redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - highlight
    - autolink
    - with_toc_data
    - tables
    - hard_wrap

# default python pygments have been replaced by pygments.rb
# todo: confirm that this is still optimal since jekyll 1.0+ is now being used
pygments: false


# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github:
  user:
  repo_count: 0
  show_profile_link: true
  skip_forks: true

# Social sharing and commenting
social:
  twitter:
    user:
    tweet_button: true

  google:
    plus_one: false
    plus_one_size: medium
    plus_user:
    # Hidden: No visible button, just add author information to search results
    plus_hidden: false

  pinboard:
    user:
    count: 3

  delicious:
    user:
    count: 3

  disqus:
    short_name:
    show_comment_count: false

  facebook:
    like: false

# Analytics settings
analytics:
  provider: google
  google:
      tracking_id: 'UA-123-12'
  getclicky:
    site_id:
  mixpanel:
      token: '_MIXPANEL_TOKEN_'
  piwik:
      baseURL: 'myserver.tld/piwik' # Piwik installation address (without protocol)
      idsite: '1'                   # the id of the site on Piwik
